name: Laravel Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-via-ftp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pdo_mysql, dom, filter, gd, json

      - name: Install Composer Dependencies
        run: composer install --no-dev --prefer-dist --no-interaction

      - name: Install Node.js Dependencies
        run: npm install

      - name: Install Laravel Mix
        run: npm install laravel-mix --save-dev

      - name: Build Assets
        run: npm run build

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Storage Link
        run: php artisan storage:link

      - name: Copy .env file
        run: |
          echo "APP_NAME=Laravel" > .env
          echo "APP_ENV=production" >> .env
          echo "APP_KEY=" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "APP_URL=https://bnc.ecowas.int" >> .env
          echo "IMAGES_PATH=storage/uploads" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=u928962285_bnc" >> .env
          echo "DB_USERNAME=u928962285_user_bnc" >> .env
          echo "DB_PASSWORD='&RN&3TT;#D0n'" >> .env

      - name: Generate Laravel Key
        run: php artisan key:generate
        env:
          APP_ENV: production
          DB_CONNECTION: mysql
          DB_HOST: localhost
          DB_PORT: 3306
          DB_DATABASE: u928962285_bnc
          DB_USERNAME: u928962285_user_bnc
          DB_PASSWORD: '&RN&3TT;#D0n'

      - name: Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: 46.202.172.253
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ../domains/bureaunationalcedeao-ci.org/public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
            **/storage/*.key
            **/.env
            **/.env.*
            **/tests/**
            **/.editorconfig
            **/.styleci.yml
            **/phpunit.xml
            **/.gitattributes
            **/.gitignore
            **/README.md
